### ISSUE TITLE
Intermittent NullPointer Exception -- Argument cannot be null

### ISSUE THREAD

**Issue by jpoole521** [jamessimone/apex-rollup#391] opened 2022-12-07 15:58 UTC
I've recently installed the package in a client org, and have a few rollups that are counting specific child Case record types and setting the value on the parent case. We're intermittently encountering an issue updating Case records, that is a variation of the below:

**We can't save this record because the “Case After Update” process failed. Give your Salesforce admin these details. This error occurred when the flow tried to update records**:_ CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: CaseTrigger: execution of AfterUpdate caused by: System.NullPointerException: Argument cannot be null. Class.RollupAsyncProcessor.retrieveAdditionalCalcItems: line 540, column 1 Class.RollupAsyncProcessor.getUpdatedLookupItemsByRollup: line 1084, column 1 Class.RollupAsyncProcessor.process: line 622, column 1 Class.RollupAsyncProcessor.runCalc: line 268, column 1 Class.Rollup.runFromTrigger: line 1572, column 1 Trigger.CaseTrigger: line 2, column 1. You can look up ExceptionCode values in the SOAP API Developer Guide. Error ID: 1117373547-24705 (-1873734586)k up ExceptionCode values in the SOAP API Developer Guide. Error ID: 1117373547-24705 (-1873734586)

The bolded portion (e.g., triggering autolaunched Flow) above may change, but the remaining error is consistent. I have not been able to consistently reproduce the issue, however, as either my admin user or the reporting user(s). Earlier today, I did encounter the issue on first attempt to save a record, but attempting once more immediately after, the record updated successfully. 

I'm continuing to attempt to reproduce the issue to setup additional debugging, but figured I'd share what we've encountered thus far. Please let me know if there's any other information that'd be helpful.

Thanks!

**Comment by jamessimone** [comment] 2022-12-08 14:14
@jpoole521 something I have been thinking about while reflecting on this issue: what's the API version of the Case trigger where you're calling Apex Rollup? I have heard from colleagues that a difference in API version between classes/triggers can lead to problems like the one you're experiencing; it's likely that if you update the API version to 56 on the Case trigger, this issue will go away. Let me know what you think.

**Comment by jpoole521** [comment] 2022-12-08 15:28
Hey @jamessimone -- thanks for the prompt response and follow up! We did update the package yesterday (looks like we must have initially installed it just ahead of the rollout of the latest version). 

I received more comprehensive steps to recreate the issue from the reporting users, but was still unable to recreate them. We're planning to setup a screenshare with them tomorrow with debug logs on for each of them, should the issue persist.

Regardless, our Case trigger is currently on API v55, so we'll give updating it to 56 a shot as well. I'll circle back with an update soon. 

Thanks again -- appreciate your collaboration and work on this tool.

**Comment by jamessimone** [comment] 2022-12-08 15:31
Sounds good - keep me updated!

**Comment by jpoole521** [comment] 2022-12-09 15:30
@jamessimone quick update -- the issue is still occurring with the API version updated on the trigger, but it seems as though it may potentially be less frequent.

I got on a screenshare with a reporting user today, who was running into consistent issues updating several Cases -- but of course when we got on the call and had debug logging configured, they were able to update about half a dozen cases without any issues. We'll keep trying to get more info.

**Comment by jamessimone** [comment] 2022-12-12 19:50
@jpoole521 in the latest package version, I added in a null check where you were experiencing this issue; that being said, I don't think it will get down to the root cause because that argument should definitively _not_ be null at that point. With that being said, if we perhaps shift where the error is occurring to a different area (by upgrading), it's possible that the new error message may continue to illuminate what the underlying issue is. Let me know!

**Comment by jamessimone** [comment] 2022-12-16 21:59
@jpoole521 any further updates on this?

**Comment by jpoole521** [comment] 2022-12-16 22:29
@jamessimone Thanks for following up. Unfortunately not -- the issue continued to be less frequent, but it was still occurring without any sensible pattern. We've temporarily rolled the implementation back (just before I saw your note about the new version) until we deploy some tech debt cleanup. 

We never experienced the issue in our primary sandbox, and the biggest variable there is that we've fully refactored several flows that were previously implemented less than efficiently (DML in loops and other poor practices). Once those refactored flows are deployed (fingers crossed for next week), we'll be rolling it back out. 

We couldn't necessarily discern a logical path between what some of the flows are doing, and the null pointer exception, but it's certainly bizarre that the issue hasn't come up even once in a sandbox that is being heavily used for testing at the moment.

**Comment by jamessimone** [comment] 2022-12-16 22:35
Gotta love those intermittent errors. If you have the nebula logger or rollup custom object logging plugin installed, you might get some additional insight into where the errors occur, but otherwise let me know! I'm going to close this issue for now - I hope you know I'm happy to help at any time (and you're free to re-open this if you get more info).

**Closed by jamessimone** 2022-12-16 22:35 UTC
