### ISSUE TITLE
rollup from parent isn't running

### ISSUE THREAD

**Issue by solo-1234** [jamessimone/apex-rollup#45] opened 2021-03-03 15:29 UTC
I just set up a rollup from a parent trigger, and it's not running. Any idea why not?

I checked `Is Rollup Started From Parent`
and added `Rollup.runFromTrigger();` to my class which runs when parents are inserted, as the line right after inserting the children.

Do I also need to tell it which child object to roll up? I'm reading through the readme but don't see anything about that when using the CMDT approach (only when using the invocable)

Thanks!

**Comment by solo-1234** [comment] 2021-03-03 16:07
I reinstalled and it's still not working :( now what?

**Comment by jamessimone** [comment] 2021-03-03 17:32
@solo-1234 hmm, I will have to investigate further. Sorry for prematurely closing this!

**Comment by solo-1234** [comment] 2021-03-03 17:32
np, thanks!

**Comment by jamessimone** [comment] 2021-03-03 18:33
@solo-1234 please reinstall - you should be all set. This was due to a small difference in behavior between the invocable/trigger based code paths that has now been consolidated, sorry about that! Once you've confirmed that you have this working, I will close the issue.

**Comment by solo-1234** [comment] 2021-03-03 18:43
still not working :(

**Comment by jamessimone** [comment] 2021-03-04 15:26
@solo-1234 #47 should address any lingering issues with the use of custom objects/custom fields - please let me know!

**Comment by solo-1234** [comment] 2021-03-04 17:17
Seems like it's working now, thanks!

**Closed** 2021-03-04 18:51 UTC
