### ISSUE TITLE
recurseThroughObjectChain error when using Grandparent rollup

### ISSUE THREAD

**Issue by johnny2678** [jamessimone/apex-rollup#409] opened 2023-02-14 19:48 UTC
First off - thanks so much for this.  Incorporating it into all of my demos. 🤓 

Sorry to create an issue for what is almost certainly user error, but I'm really stuck getting my grandparent rollup to calculate.  

Happy to reach out on Slack if you are able to collaborate there - didn't want to bother you at work :)

```
Rollup v1.5.41: finalizer logging failure from:
unexpected token: )
Inner stacktrace: Class.RollupRelationshipFieldFinder.recurseThroughObjectChain: line 375, column 1
Class.RollupRelationshipFieldFinder.getParents: line 202, column 1
Class.RollupAsyncProcessor.getCalcItemsByLookupField: line 759, column 1
Class.RollupAsyncProcessor.process: line 597, column 1
Class.RollupAsyncProcessor.QueueableProcessor.execute: line 410, column 1
```

Data Model is Travel_Approval__c -> Board_Seat__c -> Account (with Account renamed to `Boards and Commissions`)

Attempting to rollup Expenses on each Travel Approval to the Account, but only where the Travel Approval Status is 'Approved' and the Travel Approval is related to an Active Board seat, so using `Status__c = 'Approved' AND Board_Seat__r.Active__c = true` as my `child object where clause`

using Grandparent field path - `Board_Seat__r.Board_or_Commission__r.Board_Expenses__c`

currently have tried invoking from the recalc button as well as running the CMT from the Rollup App, but get the same results each time.

Rollup CMT looks like this:
![image](https://user-images.githubusercontent.com/8219743/218843664-8cfa5ca5-a3a2-423c-8c7e-1f0e7bf7d98c.png)

Additional debug logging if it helps

```
Rollup v1.5.41: about to start for RollupDeferredFullRecalcProcessor
Type: RollupDeferredFullRecalcProcessor
Invocation Point: FROM_FULL_RECALC_LWC
Is Full Recalc: true
Is No Op: false
Is Conductor: true
Inner rollups: 0
Rollup Control: {
"attributes" : {
"type" : "RollupControl__mdt",
"url" : "/services/data/v57.0/sobjects/RollupControl__mdt/m00Dn0000007cI6"
},
"OnlyRunInFlowContexts__c" : null,
"MaxRollupRetries__c" : 10,
"ShouldRunAs__c" : "Queueable",
"Label" : "Org Defaults",
"MasterLabel" : "Org Defaults",
"ShouldAbortRun__c" : false,
"Language" : "en_US",
"MaxLookupRowsBeforeBatching__c" : 3000,
"DeveloperName" : "Org_Defaults",
"BatchChunkSize__c" : 500,
"NamespacePrefix" : null,
"MaxNumberOfQueries__c" : 50,
"ShouldDuplicateRulesBeIgnored__c" : false,
"ReplaceCalcItemsAsyncWhenOverCount__c" : 1,
"ShouldRunSingleRecordsSynchronously__c" : false,
"IsDevEdOrTrialOrg__c" : false,
"TriggerOrInvocableName__c" : null,
"MaxParentRowsUpdatedAtOnce__c" : 5000,
"SystemModstamp" : "2023-01-06T21:30:18.000+0000",
"IsRollupLoggingEnabled__c" : true,
"ShouldSkipResettingParentFields__c" : false,
"QualifiedApiName" : "Org_Defaults",
"Id" : "m00Dn0000007cI6",
"IsMergeReparentingEnabled__c" : true,
"MaxQueryRows__c" : 25000
}
Query Count: 3
Is Processed?: false
Rollup Metadata: [ {
"attributes" : {
"type" : "Rollup__mdt",
"url" : "/services/data/v57.0/sobjects/Rollup__mdt/m04Dn0000002DP4IAM"
},
"SplitConcatDelimiterOnCalcItem__c" : false,
"CalcItem__c" : "Travel_Approval__c",
"LookupObject__c" : "Account",
"RollupToUltimateParent__c" : false,
"LookupFieldOnCalcItem__c" : "Board_Seat__c",
"MasterLabel" : "SUM Board Actual Expenses",
"CalcItemWhereClause__c" : "(Travel_Approval__c.Status__c = 'Approved' AND Board_Seat__r.Active__c = true)",
"IsFullRecordSet__c" : true,
"ShouldRunWithoutCustomSettingEnabled__c" : false,
"GrandparentRelationshipFieldPath__c" : "Board_Seat__r.Board_or_Commission__r.Board_Expenses__c",
"RollupOperation__c" : "SUM",
"RollupFieldOnLookupObject__c" : "Board_Expenses__c",
"Id" : "m04Dn0000002DP4IAM",
"RollupFieldOnCalcItem__c" : "Total_Expenses__c",
"RollupControl__c" : "m00Dn0000007cI6IAI",
"DeveloperName" : "SUM_Board_Actual_Expenses",
"IsRollupStartedFromParent__c" : false,
"LookupFieldOnLookupObject__c" : "Id"
} ]
Query String: "SELECT id,total_expenses__c,board_seat__c,board_seat__r.active__c\nFROM Travel_Approval__c\nWHERE Id != :objIds\nAND (((Travel_Approval__c.Status__c = 'Approved' AND Board_Seat__r.Active__c = true)))"
```

**Comment by jamessimone** [comment] 2023-02-14 20:54
@johnny2678 I will have to take a look through and get back to you. Your setup looks incredibly similar to an existing test I have but I'll have to dig around to see what the difference is and why you're running into this issue. I will be in touch if I need more info!

**Comment by jamessimone** [comment] 2023-02-15 14:38
@johnny2678 I have been trying without success to reproduce this issue locally. Would you be able to attach the two logs that get created (there will be more than two, but it's these two in particular) that start with: "Rollup v1.5.41: bulk full recalc called with data" (should be listed in the log pane under the Operation column as `/aura` and then the actual log from the Queueable (of which you've already printed an excerpt above). That would help me immensely in triangulating where your setup differs from my own, and how that extra parenthesis is being introduced into the query string. Many thanks!

**Comment by johnny2678** [comment] 2023-02-15 20:36
Well, I seem to be going backwards @jamessimone 😵‍💫 

Today, when I went to go get the logs you requested, each run (full recalc from the rollup app) never left the queue? 🤷‍♂️   I ended up having to abort from Setup->Apex Jobs.

Changed the Rollup Control from `Queueable` to `Synchronous Rollup` and the rollups ran this time and worked!?  By worked, I mean the both that the rollup ran without the error above and the rollup correctly rolled up values from the grandchild to the grandparent. Confirmed by changing the child records a few times and each time the Grandparent was updated after full recalc.


I deactivated all of my CMT flow triggers (create/update & delete).  Not sure if they were causing the error above, but had a wild hunch that I was creating a race condition with full recalcs driving triggered flows.

Not sure where this leaves me.  Is it worth troubleshooting why it doesn't work running as `Queueable`?

One other thing I noticed is that the Recalc button did not work with this grandparent rollup.  The rollup field was emptied out when I invoked from the button.  Is that expected?

Attaching logs from both the working Synchronous Rollup run from the Rollup App via CMT (which worked) and the run from the button (which didn't work)

Happy to provide org creds if that's helpful.  This is a Salesforce dev org that I own and doesn't have any customer/sensitive data.

Sorry for being all over the place - just trying to get a hang of using this since it's so powerful.  thx again!!

[Grandparent Rollup from Rollup APP - WORKS - apex-07LDn0000037OR6MAM.log](https://github.com/jamessimone/apex-rollup/files/10747310/Grandparent.Rollup.from.Rollup.APP.-.WORKS.-.apex-07LDn0000037OR6MAM.log)

[Grandparent Rollup from Rollup Button - DOESNT WORK apex-07LDn0000037ORcMAM.log](https://github.com/jamessimone/apex-rollup/files/10747332/Grandparent.Rollup.from.Rollup.Button.-.DOESNT.WORK.apex-07LDn0000037ORcMAM.log)

**Comment by jamessimone** [comment] 2023-02-15 22:57
Not to worry! Let me take a look through what you've provided and see where we land. Grandparent rollups _should_ be working through the recalc rollups button on the parent flexipage, but that button working with grandparent rollups is relatively new functionality and there could be an issue there.

**Comment by jamessimone** [comment] 2023-02-15 22:58
And I think org creds _would_ be helpful because it will make troubleshooting that much easier (as well as log generation). My email address should be listed at the bottom of the readme - I'll try to be on the lookout for that email but also feel free to ping me here in case I miss it. We will get to the bottom of these issues, for sure.

**Comment by johnny2678** [comment] 2023-02-15 23:15
org creds sent via slack. thx!

**Comment by jamessimone** [comment] 2023-02-17 22:09
Following up on this thread - I upgraded Apex Rollup in this org and was unable to repro the issue. I am going through some other feedback from @johnny2678 but am closing this for now.

**Closed by jamessimone** 2023-02-17 22:09 UTC
