### ISSUE TITLE
Currencies and changing child record values

### ISSUE THREAD

**Issue by fefris** [jamessimone/apex-rollup#415] opened 2023-02-28 01:02 UTC
Here is an issue.

Rollups via record triggered flow 

Rolling Sales Invoices to Parent account. This is the invoices present on the account. Note record currency is EURO.
![image](https://user-images.githubusercontent.com/30797036/221724613-35fad03a-1932-44eb-92a1-be0281c5aad5.png)

As expected the rollup works and rolls up the converted currency as the parent record is in AUD

![image](https://user-images.githubusercontent.com/30797036/221724704-04ef7ecc-f3c4-419a-ac2e-ca8a93dbf141.png)

However if you now edit the invoice back to Zero EURO

![image](https://user-images.githubusercontent.com/30797036/221724819-2b3b45c7-6f49-488a-9bf4-15cc010bafae.png)

You now find the total on the parent to be 0.56 AUD

![image](https://user-images.githubusercontent.com/30797036/221724910-fbaceab1-24a8-4876-9597-93499f0aa09a.png)

**Comment by fefris** [comment] 2023-02-28 01:27
Actually i have zero idea what its actually doing. If i substiture 2 EURO for the above values i get AUD 3.13 at the parent (correct if it uses the converted value) BUT if then change the invoice to 1 EURO (1.56 AUD) the parent value is 2.69 AUD (Which appears to be -0.44 AUD) - where did it get this number from.

**Comment by fefris** [comment] 2023-02-28 02:03
Changing from Upsert to Refresh in the record triggered flow seems to have fixed this. Wont close incase you want to investigate why Upsert would act wierd

**Comment by jamessimone** [comment] 2023-02-28 03:31
@fefris I will definitely take a look. I think I know what the issue is with the update case, but it's been a while since I've looked at that particular piece of the codebase so I want to be sure. it should be trivial to reproduce though - thanks very much for bringing it to my attention!

**Comment by jamessimone** [comment] 2023-03-01 19:52
@fefris just pushed the fix for that issue - it will be included in the next release. Thanks again for bringing this to my attention!

**Closed** 2023-03-02 22:00 UTC
