### ISSUE TITLE
Running from Button is Doubling Up

### ISSUE THREAD

**Issue by jkenzer** [jamessimone/apex-rollup#131] opened 2021-06-29 16:14 UTC
This one is strange since I understand the button vs the app is calling the same underlying class. In the latest release, running from the App seems to create the correct values

![image](https://user-images.githubusercontent.com/643517/123832473-38990080-d8ba-11eb-8414-14b66bf93c4b.png)

However, every time I run from the button, one of my three rollups gets doubled. I tested it on multiple parent records.

![image](https://user-images.githubusercontent.com/643517/123832538-4a7aa380-d8ba-11eb-8374-8622bcd52935.png)

Here is a copy of the Metadata

![image](https://user-images.githubusercontent.com/643517/123832589-58302900-d8ba-11eb-94c0-f5716c1e45bb.png)

The only difference between this one and the other two is that this one doesn't have an end date on the where clause.

**Comment by jamessimone** [comment] 2021-06-29 16:47
@jkenzer is this one of those parents that has a ton of child records? Anything special about it other than seeing the value get doubled?

**Comment by jamessimone** [comment] 2021-06-29 21:49
I have been looking into this and attempting to reproduce locally without success so far. There's no other rollup configured writing to `Grand Amount YTD`, right?

**Comment by jkenzer** [comment] 2021-06-29 23:48
I created a brand new currency field and updated the custom metadata to populate that field instead and got the same result. Can I send you the log without publicly posting it here to GitHub?

**Comment by jamessimone** [comment] 2021-06-30 00:12
Yes, for sure. My contact info is at the bottom of the Readme!

**Comment by jkenzer** [comment] 2021-06-30 00:17
Sent.

**Comment by jamessimone** [comment] 2021-07-01 14:55
Following up with @jkenzer on this, as the log I received for this was a bit sparse.

**Comment by jkenzer** [comment] 2021-07-02 15:36
Good news!? In my fresh full backup sandbox, I am not seeing this issue anymore. I compared the metadata setting for the rollup to the old roll-up, and they look identical, but I didn't pull from the old sandbox and push to the new sandbox. I created it fresh (well actually it was pulled from DLRS using your script and then I tweaked it to change Current Fiscal Year to 2021-04-01).

I'm going to create the other two roll-ups on this same child object and see if it has something to do with having more than one roll-up.

**Comment by jkenzer** [comment] 2021-07-02 15:56
Yeah, everything seems to be working now. I'm not sure what the issue was, but if you can't replicate it and I can't replicate it in a fresh sandbox, it must have been specific to that implementation. I think you can close this out if you want.

**Comment by jamessimone** [comment] 2021-07-02 16:02
@jkenzer I had a feeling that would happen; I think that particular Rollup was being accidentally doubled due to an unintentional retry mechanism which I tweaked in this latest release. Closing this for now!

**Closed by jamessimone** 2021-07-02 16:02 UTC
