### ISSUE TITLE
Rollup to Ultimate Parent failing in null-pointer due to currentRelationshipName still referencing Calc Item Object

### ISSUE THREAD

**Issue by dschibster** [jamessimone/apex-rollup#159] opened 2021-08-30 15:34 UTC
Just ran into this one:

- As always (at least for now) in my case, I am using the REFRESH context
- I had 3 rollups running on the same object, two going to the direct parent, one to the ultimate parent
- The ultimate Parent is of the same Object Type as the direct parent, only referenced by a different lookup
(Calc_Item__r.Direct_Parent__r.Ultimate_Parent__c is the hierarchy)
- The Lookup Field on the Metadata Type is currently still referencing Record ID. If this is supposed to already change to the parent lookup, I'd know where to start in changing my settings. :thinking: 
- Executing a REFRESH resulted in the QueueableHandler throwing a null-pointer exception with this Stack Trace:

```
Class.RollupRelationshipFieldFinder.getPotentialUltimateParent: line 264, column 1
Class.RollupRelationshipFieldFinder.isFinishedWithHierarchyTraversal: line 245, column 1
Class.RollupRelationshipFieldFinder.getParents: line 168, column 1
Class.RollupRelationshipFieldFinder.recurseThroughObjectChain: line 333, column 1
Class.RollupRelationshipFieldFinder.getParents: line 172, column 1
Class.RollupAsyncProcessor.getCalcItemsByLookupField: line 693, column 1
Class.RollupAsyncProcessor.process: line 490, column 1
Class.RollupAsyncProcessor.QueueableProcessor.execute: line 379, column 1
```

After some digging in RollupRelationshipFinder I found that while traversing the **Direct_Parent__r** level in search of the ultimate Parent, `this.currentRelationshipName` still referenced the Lookup from Calc_Item__c to Direct_Parent__c. Counter to the point of actually being in the second call of getParents(), which in this case should already try and look for the ultimate Parent.

For my case, I was able to fix this by adding:
```
this.currentRelationshipName = this.records[0].getSObjectType() != this.ultimateParent ? this.relationshipParts.remove(0) : this.metadata.UltimateParentLookup__c;
```
At the end of `recurseThroughObjectChain`, although I am not sure if this invalidates any of the other use cases I have yet to touch.

Am I missing something crucial in my settings?

**Comment by jamessimone** [comment] 2021-08-30 17:17
I wouldn’t mutate the array there, but thanks for bringing this to my attention. I will include the fix for this one in `v1.2.43` as well!

**Comment by dschibster** [comment] 2021-08-30 17:19
Agreed, looking at the way the array is handled in any other location, it does seem a little misplaced. I only added it to confirm my suspicion and decided to leave it there so that the current use case can be tested. Will gladly install the new package version over it once it comes out. :)

**Comment by jamessimone** [comment] 2021-08-30 17:29
Hmm, actually, I think that was intentional. It’s been four months since I looked over this section of the codebase though. I have to reacquaint myself!

**Comment by dschibster** [comment] 2021-08-30 17:49
If I misconfigured in the end, that is a solution I'm also fine with, but I definitely know the feeling!

**Comment by jamessimone** [comment] 2021-08-30 19:47
@dschibster I would definitely update the Calc Item Lookup Field to be `Direct_Parent__c`. There may be some _other_ issues at hand, as I haven't fully tested REFRESH with hierarchy rollups (which is to say that I've found at least one other, potentially related issue, but haven't experienced what you're reporting).

**Comment by jamessimone** [comment] 2021-08-30 19:51
Also, when you say you added:

```java
this.currentRelationshipName = this.records[0].getSObjectType() != this.ultimateParent ? this.relationshipParts.remove(0) : this.metadata.UltimateParentLookup__c;
```

to the end of `recurseThroughObjectChain`, can you be more specific - did you put that statement in _in addition to_ where that assignment is already happening on line 279?

**Comment by dschibster** [comment] 2021-08-30 20:18
If I wasn't clear enough, Direct_Parent__c is the Lookup field. Ultimate_Parent__c is only in the Hierarchy configuration.

I did actually **add** it right before getParents(). To me it didn't become obvious why the Lookup to Direct_Parent__c would get readded to the list of relationship Parts after I already traversed them, and since (in this very specific instance) I don't have a different grandparent to traverse, I saw it fit to try.

**Comment by jamessimone** [comment] 2021-09-01 13:36
@dschibster Is `Direct_Parent__c` set on as the Lookup Field On Calc Item?  Please let me know if updating that (in the event it isn't already set correctly, and removing the code change you made) fixes the issue for you. This is because for a non-grandparent-based hierarchy rollup, the `currentRelationshipName` member variable is derived from a combination of `Rollup__mdt.LookupFieldOnCalcItem__c` plus the `Rollup__mdt.UltimateParentLookup__c` field (you can see this in action in the latter half of the function `getRelationshipParts()` in `RollupRelationshipFieldFinder`. Thanks!

**Comment by dschibster** [comment] 2021-09-01 14:56
Yes, it is already set that way.
Lookup Object: `Parent Object`
Lookup Field On Lookup Object: `Record ID`
Calc Item: `Child Object`
Lookup FIeld on Calc Item: `Direct Parent`

And then, I have SUM as Operation, a WHERE condition and 
`Rollup to Ultimate Parent` set to True and
Ultimate Parent Lookup: `Ultimate Parent`

This configuration I haven't touched since I reported the issue, and it failed regardless.

**Comment by jamessimone** [comment] 2021-09-02 11:59
@dschibster thanks for the additional context. I was able to reproduce your issue and have fixed it up. I appreciate the help in tracking this one down!

**Closed** 2021-09-02 18:18 UTC
