### ISSUE TITLE
Rollups result in 0 when rolling up the same field on the same object (parent relationships)

### ISSUE THREAD

**Issue by dschibster** [jamessimone/apex-rollup#170] opened 2021-09-22 15:58 UTC
I want to preface this by saying that we put a lot of effort into analyzing errors we are facing, when we are facing them. And I can actually say that this was working one or two versions before. 😅 

However, in 1.3.3, I seem to be running into an issue with a configuration like this:

![image](https://user-images.githubusercontent.com/34553908/134378912-e45bdac4-9ead-43c6-af92-19865a9a60f6.png)
(where condition edited out)

Where the peculiarity about this would probably be that we are rolling up one field into the same field, only one level higher.

I have run several different methods:
- From Apex
- From the Mass Recalc App
- From the LWC Button

And in all of them, I haver either gotten no meaningful log other than "finished successfully", OR a log where I **successfully find Calc Items with non-zero values, but the record after rolling up still has 0 in its rollup field.**

Hopefully this isn't starting to bother 😅

**Comment by jamessimone** [comment] 2021-09-22 16:43
@dschibster never a bother. you're helping me - and everybody else using `apex-rollup` - experience the best possible version of this package. Is there anything about the omitted where clause that strikes you as special? Are you able to send the log where the calc items are retrieved but the parent item still has its value reset?

Just based off of what you're saying, I would imagine that the `RollupParentResetProcessor` (which, as you've noted, was introduced just a few versions ago) is somehow accidentally resetting the parent field. It's only supposed to do this on full recalcs (from the mass recalc app / LWC button) when there are _no_ query results (IE, no calc items), but it's possible there's some other mechanism at play that's causing this issue.

Anyway - the more I can learn about how this is occurring, the easier it will be to reproduce and ultimately patch the issue. I appreciate you working with me on this!

**Comment by jamessimone** [comment] 2021-09-22 16:57
Also - are you able to stimulate any kind of uncaught exception if you were to update your Rollup Control to run synchronously and then exercise whatever you're doing from Apex? What logging level are you using, as well? There's additional info about how evaluation of the where clause is proceeding at the `FINEST` level, for example.

**Comment by jamessimone** [comment] 2021-09-22 18:52
Both plugins should be able to coexist peacefully - indeed, there's no limit to the number of combined loggers. On my packaging org, for example, I have three loggers installed - Nebula, the Rollup Custom Object Logger, and the built in Rollup Logger. I frequently use at least the built-in logger and the Nebula adapter in tandem, so I'd love to understand what the issue is there, as well!

**Comment by dschibster** [comment] 2021-09-22 19:58
Hi @jamessimone, here's a few answers:

- The WHERE condition is the same as in my previous issue, but without the IN clause in place, so `Picklist Value comparison AND (three picklist comparisons with OR between them)`
- Running it sync does not give me an exception. It actually gave me a NoOp, which is strange, because it actualy fulfilled all criteria, and I changed the field to roll up on.
- I attached the log where I clicked the "Recalculate" Button on a valid parent record, and you will see that there are some items which find a valid capacity. Maybe it's to do with there being null-values in there? Can't tell, no NPE is thrown to say the least.
[logWithNonNullCalcItems.txt](https://github.com/jamessimone/apex-rollup/files/7213421/logWithNonNullCalcItems.txt)

I'll open an issue for the Logger fiasco. I unfortunately can't give much info on it but maybe it will give some help.

**Comment by jamessimone** [comment] 2021-09-22 21:33
@dschibster I'm noticing some `\r\n` characters in your where clause and I'm wondering if those additions are throwing off the evaluations. Can you remove the tabbed / new line characters and see if that makes any difference?

**Comment by dschibster** [comment] 2021-09-22 21:36
Good point, will report back in the morning (CEST 😅)

**Comment by jamessimone** [comment] 2021-09-22 21:42
No worries - I appreciate your time!

**Comment by dschibster** [comment] 2021-09-23 07:19
Well wouldn't you know - That was exactly the problem! I'm getting the correct values now. 
Seems like the SOQL Query evaluates correctly because it can handle carriage returns, but the condition evaluation does not.

As an aside, if we were to ask for the fields of a related record - `Parent__r.Picklist_Value__c` - does Rollup already account for things like that?

**Comment by jamessimone** [comment] 2021-09-23 13:48
@dschibster I will put in a fix for this. Oddly enough, @jongpie and I recently experienced something very much like this while working on Nebula Logger 😅. 

So the related record thing is tricky. It works in some contexts, but not others, and I have yet to do an exhaustive deep-dive on it, unfortunately. If you have a specific situation where you know for sure it's not working, please feel free to write up an issue detailing the rollup operation you were performing - that will help a ton.

**Comment by jamessimone** [comment] 2021-09-23 15:28
@dschibster just pushed a commit that will hopefully prevent characters like `\r\n\t` from interfering with where clause evaluation - once we've ironed out #171, I'll look to release that!

**Comment by dschibster** [comment] 2021-09-23 18:40
My colleague Steffen will be opening the issue for our case where we are asking the same kind of fields in the WHERE condition as here, but only going one level of hierarchy higher - Seems to not be working then. Thanks a lot!

**Closed** 2021-09-23 21:17 UTC

**Comment by jamessimone** [comment] 2021-09-23 21:19
@dschibster same here - releasing the fix for this now!
