### ISSUE TITLE
Inconsistent behaviour

### ISSUE THREAD

**Issue by cdevelin** [jamessimone/apex-rollup#466] opened 2023-07-20 12:56 UTC
Hi James,

Apologies, I'm really trying to give the roll-up a good workout.

In one of my parent objects, I have 8 rollup fields.  They are all SUM rollups of the child 'transaction' object.  For 7 out of the 8 fields, different record types or characteristics of a particular transaction cause it to roll-up into one of the 7 fields on the parent.  The 'Amount' being rolled up is always the same field, but whether the transaction is eligible for a particular field varies.

i.e. The 'where' clause for these 7 rollups are unique, such that if the transaction meets the criteria for one of those 7 fields, then it won't meet the criteria for any of the other 7 fields, and that roll-up seems pretty reliable.

However, the 8th field is a general sum of a different field from ALL transactions, without filtering.

i.e. a transaction SHOULD:
1) update one and only one of the 7 possible specific fields, and 
2) ALWAYS the 8th total field.  

i.e. every transaction should always participate in TWO rollup actions.

I'm finding the roll-up to the 8th field is unreliable.  Some times it works, sometimes it doesn't.  If I do a full-recalc just on that 8th field, it corrects itself.  (If I try to do a full-recalc on all 8 fields by the 'select all' option, then the job typically fails with too many queued items).

Do you think there is some issue with 2 rollups being triggered by a single event, and whether the random chance that the 8th field is handled first or last in the action is the reason it is unreliable?

**Comment by jamessimone** [comment] 2023-07-20 13:12
Not to worry, I don't think you're doing anything wrong and that scenario should definitely be working for you. I'd love to see a log, ideally, for the scenario where the update to the "always update field" doesn't work. The order of things shouldn't matter so this definitely sounds like a bug!

**Comment by cdevelin** [comment] 2023-07-20 13:15
Actually, I think I might have a logical explanation.

The child transaction field this '8th' rollup relies upon is often changing from a positive/negative number to zero (this 8th column is the amount still owing on a transaction, so once a transaction is fully paid, it becomes zero).

The rollup parent is the 'total owing' across all transactions.

When I pay off all the transactions which were owing in a single update, this 'amount owing' column becomes zero on every transaction.  Could it be because the amount is zero, it discards all these new 'zeroes' as having no impact on the sum?

If every payment leaves a little short, i.e. the amount owing is non-zero on every transaction, perhaps the rollup will behaves as expected.  I'll try out that theory!

Either way, I'll get the log for you now.






When it reality, the field has moved from a positive down to zero, and the SUM should similarly move down from the previous total down to zero.

**Comment by jamessimone** [comment] 2023-07-20 19:56
Thanks for sending that over! I will take a look as soon as I can. My schedule this week is a bit chaotic; probably expect to hear from me sometime early next week.

**Comment by jamessimone** [comment] 2023-07-26 15:31
@cdevelin Apologies for the delay in response. I was too optimistic about the timeframe as I'm currently on a business trip. I've started looking through the logs, though, and I'll continue to try to trace down what's going on here. I will keep you updated as time allows.

**Comment by cdevelin** [comment] 2023-07-26 20:13
@jamessimone thanks James. Appreciate the update. I'm hoping to include Apex RollUp as part of an App submitted to Security Review early next month (also utilizing Nebula Logger), so I'll let you know how it goes! 

If a Teams or Zoom session to study the issue and the surrounding config with me would make your task easier, just let me know.

**Comment by jamessimone** [comment] 2023-07-27 02:38
@cdevelin I took a pretty comprehensive look through the logs that you sent over - thank you so much for that. In particular, I honed in on the `apex-07L6D00000DOmtuUAD` log, as that seemed to contain most of the info you were discussing above.

As far as I can tell, the Assessment Period parent record ends up with the right values at the end of the rollup:

```json
{
  "Amount_Sum01__c" : 2142.61,
  "Amount_Sum20__c" : -2178.85,
  "Amount_Sum02__c" : 36.24,
}
```

Those are the fields that end up with non-zero values; the rest of them are calculated as zeros. In particular, I was paying attention to `Amount_Sum99__c`, as that appeared to be the one you were referencing (using the `Amount_unallocated__c` field) above; as far as I can tell, the zero value was appropriate for that field based on the two records being updated:

- amount starts at 2178.85
- first record amount unallocated is 0, old value is 2142.61
- amount is now 36.24
- second record amount unallocated is 0, old value is 36.24
- amount is now 0, and gets appended to the parent as such

If you _aren't_ seeing those updates flow through correctly, is it possible there's some kind of downstream automation which is occasionally rolling back updates? Apex Rollup does use `Database.update(parentRecordsToUpdate, false)` by default: updates that fail, fail silently.

@jongpie and I would be happy to get on a call with you next week to discuss and learn more about the app you're building! In the meantime, I'll also try to follow up here as time allows. I'm confident we can clear up whatever the issue is - thank you!

**Comment by cdevelin** [comment] 2023-07-27 06:15
@jamessimone Thanks for spending time looking at this.  

Looking at a fresh sample, before the process starts, I have the following parent amounts:

**Two types of Amounts owing:**
Amount_Sum01 $2142.61
Amount_Sum02 $36.24

**The Total Receipts so far:**
Amount_Sum20 -$1643.91

**This gives a balance owing:**
Amount_Sum99 $544

I then have a new receipt transaction of -$534.94

This should increase total receipts to:
Amount_Sum20  -$2178.85

and decrease the balance owing to:
Amount_Sum99 $9.06

And I can see in the log file this does indeed happen:

15:47:34.773 (5285118375)|VARIABLE_ASSIGNMENT|[293]|oldCalcItems|{"a0A0l00000FOap7EAD":{"Transfer_Other_Period__c":0.00,"LastModifiedDate":"2023-07-27T05:47:32.000Z","Total_Allocated__c":0.00,**"Amount_Sum20__c":-2169.79**,"External_ID__c":"a0C6D000009AQcsUAG_a (17 more) ...","Name":"2021","Amount_Sum02__c":36.24,"Amount_Sum00__c":0.00,"Notice_Address__c":"Mr. H J Simpson_BR_E (55 more) ...","CreatedById":"0050l000007h8KMAAY","Amount_Sum04__c":0.00,"Amount_Sum30__c":0.00,"Total_Non_Receipts__c":2178.85,"Total_Unallocated__c":9.06,"IsDeleted":false,"Date_To__c":"2021-06-30T00:00:00.000Z","CurrencyIsoCode":"AUD","SystemModstamp":"2023-07-27T05:47:32.000Z","Assessment__c":"a0C0l00000G793VEAR",**"Amount_Sum99__c":9.06**,"Amount_Sum03__c":0.00,"Date_From__c":"2020-07-01T00:00:00.000Z","Amount_Sum01__c":2142.61,"Period__c":"a0X0l000008uPOjEAM","CreatedDate":"2023-07-25T05:15:55.000Z","Id":"a0A0l00000FOap7EAD","Status__c":"Active","LastModifiedById":"0050l000007h8KMAAY","Period__r":{"Status__c":"Active","Id":"a0X0l000008uPOjEAM"}}}|0x1a69aa55


but then a few steps further on, it has reverted back to the 'old' $544 value of the Amount_Sum99:

15:47:34.773 (5285622517)|VARIABLE_ASSIGNMENT|[404]|calcItems|[{"Transfer_Other_Period__c":544.00,"LastModifiedDate":"2023-07-27T05:47:34.000Z","Total_Allocated__c":0.00,**"Amount_Sum20__c":-2178.85**,"External_ID__c":"a0C6D000009AQcsUAG_a (17 more) ...","Name":"2021","Amount_Sum02__c":36.24,"Amount_Sum00__c":0.00,"Notice_Address__c":"Mr. H J Simpson_BR_E (55 more) ...","CreatedById":"0050l000007h8KMAAY","Amount_Sum04__c":0.00,"Amount_Sum30__c":0.00,"Total_Non_Receipts__c":2178.85,"Total_Unallocated__c":9.06,"IsDeleted":false,"Date_To__c":"2021-06-30T00:00:00.000Z","CurrencyIsoCode":"AUD","SystemModstamp":"2023-07-27T05:47:34.000Z","Assessment__c":"a0C0l00000G793VEAR",**"Amount_Sum99__c":544.00**,"Amount_Sum03__c":0.00,"Date_From__c":"2020-07-01T00:00:00.000Z","Amount_Sum01__c":2142.61,"Period__c":"a0X0l000008uPOjEAM","CreatedDate":"2023-07-25T05:15:55.000Z","Id":"a0A0l00000FOap7EAD","Status__c":"Active","LastModifiedById":"0050l000007h8KMAAY","Period__r":{"Status__c":"Active","Id":"a0X0l000008uPOjEAM"}},{"Id":"a0A0l00000FOZrDEAX","Assessment__c":"a0C0l00000G793VEAR","Period__c":"a0X0l000008uPOiEAM","Date_From__c":"2019-07-01T00:00:00.000Z","CurrencyIsoCode":"AUD","Period__r":{"Status__c":"Active","Id":"a0X0l000008uPOiEAM"}},{"Id":"a0A0l00000FObRrEAL","Assessment__c":"a0C0l00000G793VEAR","Period__c":"a0X0l000008uPOkEAM","Date_From__c":"2021-07-01T00:00:00.000Z","CurrencyIsoCode":"AUD","Period__r":{"Status__c":"Active","Id":"a0X0l000008uPOkEAM"}},{"Id":"a0A0l00000FObaREAT","Assessment__c":"a0C0l00000G793VEAR","Period__c":"a0X0l000008uPOrEAM","Date_From__c":"2022-07-01T00:00:00.000Z","CurrencyIsoCode":"AUD","Period__r":{"Status__c":"Active","Id":"a0X0l000008uPOrEAM"}}]|0x303a0d1b



What I think is happening is that the 'Total Receipts' update (child 'Amount' roll-up to parent Amount_Sum20) is happening at the same time as the 'Balancing Owing' update (child 'Amount_unallocated' roll-up to Amount_Sum99) and I think the 'Amount' roll-up always takes longer because it has 7 different rollups to work through, so it almost always finishes after the Amount_unallocated roll-up, but they start at the same time.

The Amount roll-up has $544 as the balance owing when it starts, and when it finishes calculating and updates the record it sets the value to $544, because as far as that particular roll-up set is concerned, it isn't changing that value, and that's what it started with and that's what it is finishing with.

But, the Amount_unallocated rollup is finishing faster, and the Amount_Sum99 roll-up has successfully updated to $9.06, but that good work is undone by the Amount roll-up finishing later and setting it back to the original value of $544.  :(


[apex-07L0l00000QSztCEAT.zip](https://github.com/jamessimone/apex-rollup/files/12179855/apex-07L0l00000QSztCEAT.zip)

If I set the 'Amount_unallocated' rollup to trigger from the Parent, i.e. after the 7 'amount' rollups have updated the parent, the parent then recalculates the 8th 'amount_unallocated' rollup across all children, it works fine, so it is definitely some timing or collision when Rollup is trying to simultaneously update two fields on the same parent from different children fields.  If the collision is removed by forcing the second field update to run AFTER the first field is complete by triggering from the Parent, the calculation is correct.

**Comment by cdevelin** [comment] 2023-07-27 09:44
@jamessimone Thanks for spending time looking at this.  

Looking at a fresh sample with a single receipt being processed (but still demonstrating the same problem), before the process starts, I have the following parent amounts:

**Two types of Amounts owing:**
Amount_Sum01 $2142.61
Amount_Sum02 $36.24

**The Total Receipts so far:**
Amount_Sum20 -$1634.85

**This gives a balance owing:**
Amount_Sum99 $544

I then have a new receipt transaction of -$534.94

This should increase total receipts to:
Amount_Sum20  -$2169.79

and decrease the balance owing to:
Amount_Sum99 $9.06

I can see two large log files are being generated simultaneously by Apex Rollup.  One log file has the correct final 'updated records statement':

**19:21:01.348** (4027528518)|VARIABLE_ASSIGNMENT|[119]|updatedRecords|[{"Amount_Sum01__c":2142.61,"Id":"a0A0l00000FOap7EAD","Amount_Sum20__c":-2169.79,"Amount_Sum02__c":36.24,"Amount_Sum00__c":0.00,"Amount_Sum04__c":0.00,"Amount_Sum30__c":0.00,**"Amount_Sum99__c":9.06**,"Amount_Sum03__c":0.00,"CurrencyIsoCode":"AUD"}]|0x1e92c28e

Unfortunately, the other big log file finishes 2 seconds later, and it has the wrong (old) amount, and it is the final update:

**19:21:03.24** (5716701852)|VARIABLE_ASSIGNMENT|[119]|updatedRecords|[{"Amount_Sum01__c":2142.61,"Id":"a0A0l00000FOap7EAD","Amount_Sum20__c":-2169.79,"Amount_Sum02__c":36.24,"Amount_Sum00__c":0.00,"Amount_Sum04__c":0.00,"Amount_Sum30__c":0.00,**"Amount_Sum99__c":544.00**,"Amount_Sum03__c":0.00,"CurrencyIsoCode":"AUD"}]|0x7f49c66




[apex-logs_20230727.zip](https://github.com/jamessimone/apex-rollup/files/12181791/apex-logs_20230727.zip)

**Comment by cdevelin** [comment] 2023-07-27 09:45
P.S. I follow you on LinkedIn - send me a message and I'd be happy to have a chat with you and Jonathan on the app we are building.

**Comment by cdevelin** [comment] 2023-07-27 19:11
@jamessimone Hi James,
The insert of the new receipt child record and the update of the existing payment child record happens within the same transaction (it is a single flow doing it at the moment, eventually that will be an APEX job , but same logic).

I have got an existing standard SF master-detail rollup happening to cross-check the APEX RollUp results to two separate fields on the parent (Total_Allocated and Total_Unallocated) , so does SF perform its own rollups asynchronously? I added these so I can easily spot when APEX Rollup has failed , since Amount_Sum99 (Balance Owing) should ALWAYS equal Total_Unallocated (and I was getting inconsistent results from APEX Rollup before I added these standard Master/Detail Rollups).


I could imagine that standard SF Rollup could be causing the parent to change while APEX Rollup is doing it's thing to the other fields, but other than that, there is only 1 DML transaction triggering APEX Rollup.

I will try those other settings you suggest.

(NB At the moment, most of the time I can't get the full recalculate process to work to even fix things afterwards, even targeting 1 of the 8 Rollups at a time. It is just timing out and failing on the APEX job.  If I reduce the batch sizes in the metadata by 90%. (Eg 25000 record limit becomes 2500) the full recalculate can complete but the recalculated results are wrong, they have not recalculated from scratch but are additive).

There are no other flows happening on the child records, and the APEX Rollup trigger is the only trigger, but there are 8 APEX Rollups set on the child record with different WHERE clauses and target parent fields.

**Comment by jamessimone** [comment] 2023-07-27 20:05
If you're doing this from within flow, are you using the `Defer Processing` option? I would also try setting that to true and calling the second flow action `Process Deferred Rollups` at the end of your flow. At the moment, it appears that your flow is calling Apex Rollup twice instead of once. Alternatively, if you _can_ use a trigger, using `Rollup.runFromTrigger();` might be easier to properly boxcar the insert/updates.

I can't comment on the out of the box rollups processing, other than to say you can somewhat infer what's going on under the hood based on the order of operations.

The only setting you could try updating on the Rollup Control record to improve the performance of the batch full recalc would be the Batch Chunk Size number. Nothing else should need to change. On the other hand, it's very strange that there's any timeout occurring whatsoever - based on the logs you've sent me, everything finishes extremely quickly.

**Comment by cdevelin** [comment] 2023-07-27 20:47
@jamessimone hi James,

Sorry, you've misunderstood or I haven't been clearly explaining my set up.

I am not calling APEX Rollup within the flow. The flow just does a normal set of record inserts & updates, it does not call any APEX Rollup actions itself when it concludes.

After the flow has completed its transaction, the trigger on the child object, as per the recommended instructions, runs APEX Rollup, using the Rollup.runFromTrigger(). 

But as you can see, two different APEX Rollup processes seem to be  being spawned by that trigger from the concluding flow transaction (which I would observe contains both an insert and an update to the triggered object).

I'm yet to try those settings changes you suggest, but it's the start of a new day here, so I'll let uou know how it goes.

**Comment by jamessimone** [comment] 2023-08-02 21:36
Keeping a paper trail as we've moved some of this correspondence to email - testing a fix for this currently, with initial results looking promising. If all goes well, this update will go out in the next release.

**Closed** 2023-08-03 20:03 UTC
