### ISSUE TITLE
Attempt to de-reference null when running a rollup from the Recalculate Rollup LWC

### ISSUE THREAD

**Issue by dhoechst** [jamessimone/apex-rollup#75] opened 2021-04-09 16:18 UTC
I'm trying to troubleshoot why my rollup isn't rolling up the right number in my trigger. I'm trying to force recalculation by requesting the rollup from the Recalculate Rollup tab. When I do, I get this error:

![image](https://user-images.githubusercontent.com/1051263/114210126-a1f11f00-991c-11eb-9ff0-5f76c2c5e7ff.png)

Here's the values I entered, just in case I'm doing something wrong.

![image](https://user-images.githubusercontent.com/1051263/114210323-de247f80-991c-11eb-8ab9-e7d91e126f12.png)

**Comment by jamessimone** [comment] 2021-04-09 18:33
@dhoechst this is beyond puzzling. At present, I believe the issue is due to a regression in the LWC - the handler that picks up field entries as you type them in is currently broken. It has been working without issue since the introduction of this component, and is plucked straight from the `lwc-recipes` methodology for taking values from `<lightning-input>` fields.

I am going to try to reach out to the LWC team to see if this is a known issue - I will keep you updated. Thanks so much for reporting.

**Comment by jamessimone** [comment] 2021-04-09 19:47
@dhoechst after talking with the LWC team, this appears to be an unintended regression in the way events are bubbled through the Shadow DOM. Interestingly, I've had a few people test in different environments and it's a mixed bag - the way the code is, at present, works for some people and not for others. The salesforce instances you and I are on have the latest LWC version, which is where the error is originating from.

I'm waiting for a bit more information (on fix timeline, for one), but I also have a possible workaround that I'm looking at. Depending on the fix timeline, I'll include that with `v1.2.7` (where I also hope to have #74 and #69 addressed). In the meantime, are you able to run the job using the CMDT part of this component?

**Comment by dhoechst** [comment] 2021-04-09 21:24
Yes, I was able to use CMDT to trigger the rollup. (I'm bashful to say I finally figured out I didn't create the new custom setting needed.)

**Comment by jamessimone** [comment] 2021-04-09 21:34
@dhoechst it's all good. Things have been moving pretty fast on this project. Glad to hear we've got at least a workaround in place for you for now!

**Comment by jamessimone** [comment] 2021-04-14 18:53
@dhoechst managed to triage the original issue with the LWC and Locker teams today - this ended up being a problem on my end with the Locker service and the use of additional exports in my LWC file - basically was trying to cut down on some duplication between the LWC and the jest tests for it, which had the unintentional effect of breaking the end-to-end version of the event handler used to track the entries people were making on the input fields prior to starting the rollup. This will be fixed in the release for `v1.2.9`

Thanks again for bringing it to my attention!

**Closed** 2021-04-16 19:55 UTC
